/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs_jniexample_FibonacciNative */

#ifndef _Included_rtrk_pnrs_jniexample_FibonacciNative
#define _Included_rtrk_pnrs_jniexample_FibonacciNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs_jniexample_FibonacciNative
 * Method:    get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_rtrk_pnrs_jniexample_FibonacciNative_get
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
